version: "3.9"
services:
  laravel:
    build: .
    ports:
    - "8080:80"
    volumes:
      - awwal_host:/var/www/html/
      - ./apache_logs:/var/log/apache2
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: laravel-mysql
    volumes:
      - ./mysql_logs:/var/lib/mysql
volumes:
  awwal_host:
